<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Azure.AI.Vision.ImageAnalysis" Version="1.0.0" />
    <PackageReference Include="OpenCvSharp4" Version="4.11.0.20250507" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.11.0.20250507" />
    <PackageReference Include="TesseractOCR" Version="5.5.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FinTracker.Assets\FinTracker.Assets.csproj" />
    <ProjectReference Include="..\FinTracker.Models\FinTracker.Models.csproj" />
    <ProjectReference Include="..\FinTracker.Repositories\FinTracker.Repositories.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\Dell\.nuget\packages\tesseractocr\5.5.1\build\\..\x64\leptonica-1.85.0.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\Dell\.nuget\packages\tesseractocr\5.5.1\build\\..\x64\tesseract55.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\Dell\.nuget\packages\tesseractocr\5.5.1\build\\..\x86\leptonica-1.85.0.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\Dell\.nuget\packages\tesseractocr\5.5.1\build\\..\x86\tesseract55.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\Dell\.nuget\packages\tesseractocr\5.5.1\build\\..\x64\leptonica-1.85.0.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\Dell\.nuget\packages\tesseractocr\5.5.1\build\\..\x64\tesseract55.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\Dell\.nuget\packages\tesseractocr\5.5.1\build\\..\x86\leptonica-1.85.0.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\Dell\.nuget\packages\tesseractocr\5.5.1\build\\..\x86\tesseract55.dll" />
  </ItemGroup>

</Project>
