<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Logos\aldi.png" />
    <None Remove="Logos\auchan.png" />
    <None Remove="Logos\biedronka.png" />
    <None Remove="Logos\carrefour.png" />
    <None Remove="Logos\circle-k.png" />
    <None Remove="Logos\hebe.png" />
    <None Remove="Logos\intermarche.png" />
    <None Remove="Logos\kaufland.png" />
    <None Remove="Logos\kfc.png" />
    <None Remove="Logos\komputronik.png" />
    <None Remove="Logos\lewiatan.png" />
    <None Remove="Logos\lidl.png" />
    <None Remove="Logos\mcdonalds.png" />
    <None Remove="Logos\media-expert.png" />
    <None Remove="Logos\media-markt.png" />
    <None Remove="Logos\netto.png" />
    <None Remove="Logos\orlen.jpg" />
    <None Remove="Logos\piekarnia-pod-telegrafem.jpg" />
    <None Remove="Logos\rossman.jpg" />
    <None Remove="Logos\rtv-euro-agd.png" />
    <None Remove="Logos\spolem.png" />
    <None Remove="Logos\stokrotka.png" />
    <None Remove="Logos\wafelek.jpg" />
    <None Remove="Logos\x-kom.png" />
    <None Remove="Logos\zabka.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Logos\aldi.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Logos\auchan.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Logos\biedronka.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Logos\carrefour.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Logos\circle-k.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Logos\hebe.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Logos\intermarche.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Logos\kaufland.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Logos\kfc.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Logos\komputronik.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Logos\lewiatan.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Logos\lidl.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Logos\mcdonalds.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Logos\media-expert.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Logos\media-markt.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Logos\netto.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Logos\orlen.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Logos\piekarnia-pod-telegrafem.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Logos\rossman.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Logos\rtv-euro-agd.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Logos\spolem.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Logos\stokrotka.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Logos\wafelek.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Logos\x-kom.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Logos\zabka.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
